config/routes.rb
Lms::Application.routes.draw do
  resources :permissions
  resources :grade_levels
  resources :answers
  resources :questions
  resources :quizzes
  resources :users
  resources :institutions
  resources :classrooms
  resources :submission_types
  resources :assignment_types
  resources :assignments

  match '/facebook/login' => 'facebook#login', :as => :facebook_login
  match '/take_quiz/:id' => 'pages#take_quiz', :as => 'take_quiz', :via => 'get'
  match '/take_quiz' => 'pages#take_quiz_create', :as => 'take_quiz_create', :via => 'post'
  match '/join_class/:id' => 'pages#join_class', :as => 'join_class', :via => 'get'
  match '/profile/:id' => 'users#show', :as => 'profile', :via => 'get'

  root :to => 'pages#index'
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  attr_accessible :address, :city, :country, :name, :postal_code, :region

  validates :name, presence: true
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @institutions }
    end
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
    @institution = Institution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @institution }
    end
  end

  # GET /institutions/new
  # GET /institutions/new.json
  def new
    @institution = Institution.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @institution }
    end
  end

  # GET /institutions/1/edit
  def edit
    @institution = Institution.find(params[:id])
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(params[:institution])

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render json: @institution, status: :created, location: @institution }
      else
        format.html { render action: "new" }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /institutions/1
  # PUT /institutions/1.json
  def update
    @institution = Institution.find(params[:id])

    respond_to do |format|
      if @institution.update_attributes(params[:institution])
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution = Institution.find(params[:id])
    @institution.destroy

    respond_to do |format|
      format.html { redirect_to institutions_url }
      format.json { head :no_content }
    end
  end
end

app/views/institutions/_form.html.erb
<%= form_for @institution, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render "shared/error_messages", :target => @institution %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :region, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :region, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :postal_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :postal_code, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                institutions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<%- model_class = @institution.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/institutions/index.html.erb
<%- model_class = Institution.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:region) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= link_to institution.name, institution_path(institution) %></td>
        <td><%= institution.region %></td>
        <td><%= institution.country %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_institution_path(institution), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      institution_path(institution),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_institution_path,
            :class => 'btn btn-primary' %>

app/views/institutions/new.html.erb
<%- model_class = @institution.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/institutions/show.html.erb
<%- model_class = @institution.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @institution.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @institution.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @institution.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:region) %>:</strong></dt>
  <dd><%= @institution.region %></dd>
  <dt><strong><%= model_class.human_attribute_name(:postal_code) %>:</strong></dt>
  <dd><%= @institution.postal_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @institution.country %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              institutions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_institution_path(@institution), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              institution_path(@institution),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>