config/routes.rb
Lms::Application.routes.draw do
  resources :permissions
  resources :grade_levels
  resources :answers
  resources :questions
  resources :quizzes
  resources :users
  resources :institutions
  resources :classrooms
  resources :submission_types
  resources :assignment_types
  resources :assignments

  match '/facebook/login' => 'facebook#login', :as => :facebook_login
  match '/take_quiz/:id' => 'pages#take_quiz', :as => 'take_quiz', :via => 'get'
  match '/take_quiz' => 'pages#take_quiz_create', :as => 'take_quiz_create', :via => 'post'
  match '/join_class/:id' => 'pages#join_class', :as => 'join_class', :via => 'get'
  match '/profile/:id' => 'users#show', :as => 'profile', :via => 'get'

  root :to => 'pages#index'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def new
    @quiz = Quiz.new
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def create
    @quiz = Quiz.new(params[:quiz])

    if @quiz.save
      redirect_to @quiz, notice: 'Quiz was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @quiz = Quiz.find(params[:id])

    if @quiz.update_attributes(params[:quiz])
      redirect_to @quiz, notice: 'Quiz was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy
    redirect_to quizzes_url
  end
end

app/views/quizzes/_form.html.erb
<%= form_for @quiz, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render "shared/error_messages", :target => @quiz%>
  <div class="control-group">
    <%= f.label :assignment_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :assignment_id, Assignment.all, :id, :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                quizzes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<%- model_class = @quiz.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quizzes/index.html.erb
<%- model_class = Quiz.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:assignment_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= (link_to quiz.assignment.name, quiz_path(quiz)) unless quiz.assignment.blank? %></td>
        <td><%= quiz.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_quiz_path(quiz), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      quiz_path(quiz),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_quiz_path,
            :class => 'btn btn-primary' %>

app/views/quizzes/new.html.erb
<%- model_class = @quiz.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quizzes/show.html.erb
<%- model_class = @quiz.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:assignment_id) %>:</strong></dt>
  <dd><%= link_to @quiz.assignment.name, assignment_path(@quiz.assignment) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @quiz.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              quizzes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_quiz_path(@quiz), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              quiz_path(@quiz),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>