config/routes.rb
Lms::Application.routes.draw do
  resources :permissions
  resources :grade_levels
  resources :answers
  resources :questions
  resources :quizzes
  resources :users
  resources :institutions
  resources :classrooms
  resources :submission_types
  resources :assignment_types
  resources :assignments

  match '/facebook/login' => 'facebook#login', :as => :facebook_login
  match '/take_quiz/:id' => 'pages#take_quiz', :as => 'take_quiz', :via => 'get'
  match '/take_quiz' => 'pages#take_quiz_create', :as => 'take_quiz_create', :via => 'post'
  match '/join_class/:id' => 'pages#join_class', :as => 'join_class', :via => 'get'
  match '/profile/:id' => 'users#show', :as => 'profile', :via => 'get'

  root :to => 'pages#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :correct, :name, :question_id

  validates :name, presence: true

  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def new
    @answer = Answer.new
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def create
    @answer = Answer.new(params[:answer])

    if @answer.save
      redirect_to @answer, notice: 'Answer was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @answer = Answer.find(params[:id])

    if @answer.update_attributes(params[:answer])
      redirect_to @answer, notice: 'Answer was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to answers_url
  end
end

app/views/answers/_form.html.erb
<%= form_for @answer, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render "shared/error_messages", :target => @answer %>
  <div class="control-group">
    <%= f.label :question_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :question_id, Question.all, :id, :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :correct, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :correct, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                answers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<%- model_class = @answer.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/answers/index.html.erb
<%- model_class = Answer.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:question_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:correct) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= (link_to answer.question.name, answer_path(answer)) unless answer.question.blank? %></td>
        <td><%= answer.name %></td>
        <td><%= answer.correct %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_answer_path(answer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      answer_path(answer),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_answer_path,
            :class => 'btn btn-primary' %>

app/views/answers/new.html.erb
<%- model_class = @answer.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/answers/show.html.erb
<%- model_class = @answer.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:question_id) %>:</strong></dt>
  <dd><%= @answer.question_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @answer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:correct) %>:</strong></dt>
  <dd><%= @answer.correct %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              answers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_answer_path(@answer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              answer_path(@answer),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>